version: '2.4'

volumes:
  static:
  front:

services:
  django:
    build:
      context: .
      dockerfile: ./config/django/Dockerfile
    volumes:
      - static:/static/
    env_file:
      - ./config/django/environment.env
      - ./config/postgres/environment.env
    restart: on-failure
    cpus: 0.5
    mem_limit: 200M

  postgres:
    image: postgres:12.2
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    env_file:
      - ./config/postgres/environment.env
    restart: on-failure

  front:
    build:
      context: .
      dockerfile: config/front/Dockerfile
    volumes:
      - front:/front/
    restart: on-failure

  nginx:
    image: nginx:1.18.0-alpine
    volumes:
      - static:/static:ro
      - front:/front:ro
      - ./config/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./config/nginx/proxy_params:/etc/nginx/proxy_params
    restart: on-failure
    ports:
      - "8910:80"
